repos:
  - repo: https://github.com/thlorenz/doctoc.git
    rev: "v1.4.0"
    hooks:
      - id: doctoc
        files: ^README\.md|CONTRIBUTING\.md$
  - repo: local
    hooks:
      -   id: black
          name: Formats python files using black
          language: system
          entry: black core/
          pass_filenames: false
          always_run: true
      -   id: shellcheck
          name: Check Shell scripts syntax corectness
          language: docker_image
          entry: koalaman/shellcheck:stable -e SC1091 -e SC2181
          types: [shell]
      -   id: pylint
          name: Runs pylint for core/app
          language: system
          entry: pylint --rcfile=core/pylintrc --output-format=colorized core/app
          pass_filenames: false
          always_run: true
      -   id: pylint_test
          name: Runs pylint for core/tests
          language: system
          entry: pylint --rcfile=core/pylintrc --output-format=colorized --disable="unused-argument,protected-access,invalid-name" core/app
          pass_filenames: false
          always_run: true
      -   id: pytest
          name: Runs all unit tests with pytest
          language: system
          entry: pytest --cov=core/app --cov-config core/.coveragerc
          pass_filenames: false
          always_run: true
