# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

ruby '2.6.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'
# Use postgresql as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma'
# Integrate SassC-Ruby with Rails
gem 'sassc-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails'

# for railties app_generator_test
gem 'bootsnap', require: false

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'
# Use Redis adapter to run Action Cable in production
gem 'redis'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# For getting rid of erb
gem 'slim-rails'

# To make generating BTC wallets easy
gem 'money-tree'

# Easiest way to add multi-environment yaml settings to Rails
gem 'config'

# File Attachment toolkit for Ruby applications
gem 'shrine'
# High-level image processing helper methods with libvips and ImageMagick/GraphicsMagick
gem 'image_processing'

# The ruby gnuplot gem
gem 'gnuplot'

# Makes http fun again!
gem 'httparty'

# Encryption Utilities for Web Push protocol
gem 'webpush'
# Use Service Worker with the Rails asset pipeline
gem 'serviceworker-rails'

# A Ruby interface to the Twitter API. http://www.rubydoc.info/gems/twitter
gem 'twitter'

# Simple, efficient background processing for Ruby
gem 'sidekiq'
# Lightweight job scheduler extension for Sidekiq
gem 'sidekiq-scheduler'

# Semantic UI, converted to Sass and ready to drop into Rails & Compass
gem 'semantic-ui-sass', github: 'doabit/semantic-ui-sass'

# Migrate and update data alongside your database structure.
gem 'data_migrate'

group :production do
  # Raven is a Ruby client for Sentry
  gem "sentry-raven"
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  # RSpec for Rails-3+
  gem 'rspec-rails'
  # Factory Bot ♥ Rails https://thoughtbot.com/services/ruby-on-rails
  gem 'factory_bot_rails'
  # A library for generating fake data such as names, addresses, and phone numbers.
  gem 'faker'
  # A runtime developer console and IRB alternative with powerful introspection capabilities
  gem 'pry'
end

group :test do
  # The instafailing RSpec progress bar formatter
  gem 'fuubar'
  # Library for stubbing and setting expectations on HTTP requests in Ruby.
  gem 'webmock'
  # In-memory storage for Shrine
  gem 'shrine-memory'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'listen'
  gem 'web-console'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen'
  # To make docker debugging possible
  gem 'debase'
  gem 'ruby-debug-ide'
  # A Ruby static code analyzer and formatter, based on the community Ruby style guide
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
  # Patch-level verification for Bundler
  gem 'bundler-audit', require: false
end
