# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

ruby '~> 2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'
# Use postgresql as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma'
# Use SCSS for stylesheets
gem 'sass-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# for railties app_generator_test
gem 'bootsnap', require: false

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'
# Use Redis adapter to run Action Cable in production
gem 'redis'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Manage Users with Devise
gem 'devise'

# For getting rid of erb
gem 'slim-rails'

# To make generating BTC wallets easy
gem 'money-tree'

# Easiest way to add multi-environment yaml settings to Rails
gem 'config'

# File Attachment toolkit for Ruby applications
gem 'shrine'
# High-level image processing helper methods with libvips and ImageMagick/GraphicsMagick
gem 'image_processing'

# The ruby gnuplot gem
gem 'gnuplot'

# Makes http fun again!
gem 'httparty'

# Encryption Utilities for Web Push protocol
gem 'webpush'
# Use Service Worker with the Rails asset pipeline
gem 'serviceworker-rails'

# A Ruby interface to the Twitter API. http://www.rubydoc.info/gems/twitter
gem 'twitter'

# Simple, efficient background processing for Ruby
gem 'sidekiq'
# Lightweight job scheduler extension for Sidekiq
gem 'sidekiq-scheduler'

gem 'sinatra'
# Semantic UI, converted to Sass and ready to drop into Rails & Compass
gem 'semantic-ui-sass', github: 'doabit/semantic-ui-sass'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  # RSpec for Rails-3+
  gem 'rspec-rails'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'listen'
  gem 'web-console'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen'
  # To keep the code clean
  gem 'rubocop'
  # To make docker debugging possible
  gem 'debase'
  gem 'ruby-debug-ide'
  # A Ruby static code analyzer and formatter, based on the community Ruby style guide
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
