"""empty message

Revision ID: 90dcef917a32
Revises: 
Create Date: 2019-03-20 14:21:04.969858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dcef917a32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charting', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('charting', 'last_tsmp')
    op.add_column('levels', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('levels', 'tsmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('tsmp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('levels', 'time')
    op.add_column('charting', sa.Column('last_tsmp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('charting', 'time')
    # ### end Alembic commands ###
